import { WindowOptions } from "./types";

// Partial<WindowOptions>ではなく、全てのキーを定義して型安全にする
export const defaultConfig: Required<WindowOptions> = {
	id: null,
	ifExists: "focus",
	title: "New Window",
	icon: null,
	x: "auto",
	y: "auto",
	width: 500,
	height: 400,
	minWidth: 200,
	minHeight: 150,
	resizableX: true,
	resizableY: true,
	movable: true,
	closable: true,
	minimizable: true,
	maximizable: true,
	maximizableOnDblClick: true,
	enableShortcuts: true,
	controlsPosition: "right",
	content: {
		html: "",
		iframe: {
			src: "",
			srcdoc: "",
			allow: "",
			referrerPolicy: "",
			loading: "lazy",
			sandbox: "",
			loadWinLet: false,
		},
		template: "",
	},
	menu: [],
	menuStyle: "default",
	tabs: [],
	tabStyle: "default",
	tabOptions: {
		reorderable: false,
		closable: false,
		addable: false,
		detachable: false,
		mergeable: false,
		allowIncomingMerge: false,
		onAdd: undefined,
		onMergeAttempt: undefined,
	},
	contextMenu: [],
	focus: true,
	onOpen: () => {},
	onClose: () => {},
	onFocus: () => {},
	onBlur: () => {},
	onResize: () => {},
	onMove: () => {},
	onReload: () => {},

	_isPopup: false,
	_parent: null,
};
